"""Promote the trained baseline model into a frozen Champion Package.

Two strictly separate lifecycle actions live here:

* :func:`promote_baseline_model` creates an immutable Champion Package
  (champion contract, runtime contracts, trusted adapter, model bundle,
  promotion receipt) under ``runtime/champions/<champion_id>/``.
  Creation is atomic and idempotent: identical content returns the
  existing package; different content under the same id fails.
* :func:`activate_champion` flips the small ``active-champion.json``
  pointer after re-verifying schema and hash bindings.

Live inference must never call these; it only reads the active pointer.
"""

from __future__ import annotations

import hashlib
import inspect
import json
import os
import shutil
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ashare_quant_core import UniverseMember, UniverseSnapshot
from jsonschema import Draft202012Validator, FormatChecker

from .backtest import BacktestReport
from .features import MIN_OBSERVATIONS, _return, compute_feature_row

ADAPTER_ID = "ml-baseline-adapter/v1"
STRATEGY_ID = "ml-baseline"
STRATEGY_VERSION = "v1"
UNIVERSE_POLICY_ID = "pilot-audit-universe"
UNIVERSE_POLICY_VERSION = "v1"
PILOT_MARKET_RULES: dict[str, Any] = {
    "contract_id": "market-rules",
    "schema_version": "1.0.0",
    "rules_id": "pilot-a-share-market/v1",
    "segments": [
        {
            "segment_id": f"{board}-normal",
            "board": board,
            "security_status": "normal",
            "valid_from": "2020-01-01",
            "valid_to": None,
            "lot_size": 100,
            "sell_t_plus": 1,
            "price_limit_pct": 0.2 if board in {"gem", "star"} else 0.1,
        }
        for board in ("main", "gem", "star")
    ],
}
PILOT_EXECUTION_POLICY: dict[str, Any] = {
    "contract_id": "execution-policy",
    "schema_version": "1.0.0",
    "policy_id": "pilot-next-open/v1",
    "decision_timing": "daily_close",
    "execution_timing": "next_open",
    "slippage_bps": 10,
    "impact_model": "linear_participation",
    "maximum_participation_rate": 0.05,
    "enforce_t_plus_one": True,
}
PILOT_PORTFOLIO_RISK: dict[str, Any] = {
    "contract_id": "portfolio-risk",
    "schema_version": "1.0.0",
    "risk_id": "pilot-aggressive-long-only/v1",
    "max_positions": 6,
    "max_single_weight": 0.25,
    "max_theme_weight": 1.0,
    "max_gross_exposure": 1.0,
    "rebalance_threshold": 0.02,
}

ADAPTER_SOURCE_TEMPLATE = '''\
"""Baseline ML adapter generated by research promotion. Do not edit by hand."""

from __future__ import annotations

import hashlib
import math
import pickle
from collections import defaultdict
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path

import numpy as np
import sklearn
from ashare_quant_core import DailyBar, DatasetSnapshot, TargetPosition, UniverseSnapshot

FEATURE_NAMES = {feature_names}
MIN_OBSERVATIONS = {min_observations}


{return_source}


{compute_feature_row_source}


class BaselineMLStrategy:
    strategy_id = "{strategy_id}"
    strategy_version = "{strategy_version}"

    def __init__(self, *, bundle, top_k: int, per_weight: float) -> None:
        self._models = bundle["models"]
        self._horizons = tuple(bundle["horizons"])
        self._top_k = top_k
        self._per_weight = per_weight

    def _score(self, matrix):
        predictions = np.column_stack(
            [self._models[horizon].predict(matrix) for horizon in self._horizons]
        )
        return predictions.mean(axis=1)

    def target_positions(
        self,
        *,
        as_of: date,
        dataset_snapshot: DatasetSnapshot,
        universe_snapshot: UniverseSnapshot,
    ) -> tuple[TargetPosition, ...]:
        history: dict[str, list[DailyBar]] = defaultdict(list)
        for bar in dataset_snapshot.bars(through=as_of):
            if bar.symbol in universe_snapshot.eligible_symbols:
                history[bar.symbol].append(bar)

        candidates: list[tuple[str, tuple[float, ...]]] = []
        for symbol in sorted(history):
            ordered = sorted(history[symbol], key=lambda item: item.trade_date)
            if ordered[-1].trade_date > as_of:
                continue
            values = compute_feature_row(ordered, len(ordered) - 1)
            if values is None:
                continue
            candidates.append((symbol, values))
        if not candidates:
            return ()

        matrix = np.asarray([values for _, values in candidates], dtype=float)
        scores = self._score(matrix)
        ranked = sorted(
            ((symbol, float(score)) for (symbol, _), score in zip(candidates, scores)),
            key=lambda item: (-item[1], item[0]),
        )
        return tuple(
            TargetPosition(symbol=symbol, target_weight=self._per_weight)
            for symbol, _ in ranked[: self._top_k]
        )


def build_strategy(config: Mapping[str, object]) -> BaselineMLStrategy:
    package_dir = Path(__file__).resolve().parent
    bundle_path = package_dir / str(config["model_bundle_file"])
    if bundle_path.is_symlink():
        raise ValueError("model bundle cannot be a symlink")
    content = bundle_path.read_bytes()
    if hashlib.sha256(content).hexdigest() != config["model_bundle_sha256"]:
        raise ValueError("model bundle hash mismatch")
    bundle = pickle.loads(content)
    if bundle.get("sklearn_version") != sklearn.__version__:
        raise ValueError("model bundle sklearn version mismatch")
    if bundle.get("numpy_version") != np.__version__:
        raise ValueError("model bundle numpy version mismatch")
    return BaselineMLStrategy(
        bundle=bundle,
        top_k=int(config["top_k"]),
        per_weight=float(config["per_weight"]),
    )
'''


class ChampionPackageError(ValueError):
    """Raised when a frozen champion package cannot be created or verified."""


def canonical_json_bytes(document: Mapping[str, Any]) -> bytes:
    return json.dumps(document, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()


def canonical_json_sha256(document: Mapping[str, Any]) -> str:
    return hashlib.sha256(canonical_json_bytes(document)).hexdigest()


def _write_json(path: Path, document: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_json_bytes(document) + b"\n")


def _load_schema(repository_root: Path, contract_id: str) -> dict[str, Any]:
    registry = json.loads((repository_root / "contracts/registry.json").read_text(encoding="utf-8"))
    for entry in registry["contracts"]:
        if entry["contract_id"] == contract_id:
            schema = json.loads((repository_root / "contracts" / entry["schema"]).read_text())
            if isinstance(schema, dict):
                return schema
    raise ValueError(f"missing schema for {contract_id}")


def build_universe_document(
    *,
    symbols: tuple[str, ...],
    as_of: str,
    generated_at: str,
    dataset_manifest: Mapping[str, Any],
) -> dict[str, Any]:
    if not symbols:
        raise ValueError("pilot universe requires at least one symbol")
    valid_from = str(dataset_manifest["files"][0]["min_trade_date"])
    members = [
        {
            "symbol": symbol,
            "valid_from": valid_from,
            "valid_to": None,
            "eligible": True,
            "reason_codes": ["PILOT_MEMBER", "DATA_COMPLETE"],
        }
        for symbol in sorted(set(symbols))
    ]
    return {
        "contract_id": "universe",
        "schema_version": "2.0.0",
        "universe_id": "pilot-audit-universe-pit/v1",
        "universe_policy_id": UNIVERSE_POLICY_ID,
        "universe_policy_version": UNIVERSE_POLICY_VERSION,
        "as_of": as_of,
        "generated_at": generated_at,
        "source": "pilot-universe-generator/v1",
        "source_version": "v1",
        "quality_status": "pass",
        "members": members,
    }


def load_pilot_cost_model(repository_root: Path) -> dict[str, Any]:
    document = json.loads(
        (repository_root / "contracts/examples/cost-model.example.json").read_text(
            encoding="utf-8"
        )
    )
    if not isinstance(document, dict):
        raise ValueError("cost model example must be an object")
    return document


def _generate_adapter_source(feature_names: tuple[str, ...]) -> str:
    return ADAPTER_SOURCE_TEMPLATE.format(
        feature_names=repr(feature_names),
        min_observations=MIN_OBSERVATIONS,
        return_source=inspect.getsource(_return),
        compute_feature_row_source=inspect.getsource(compute_feature_row),
        strategy_id=STRATEGY_ID,
        strategy_version=STRATEGY_VERSION,
    )


@dataclass(frozen=True)
class PromotionPaths:
    runtime_root: Path
    champions_dir: Path
    package_dir: Path
    contracts_dir: Path
    adapter_root: Path
    champion_path: Path
    receipt_path: Path
    promotion_report_path: Path
    model_bundle_path: Path
    champion_id: str
    champion_sha256: str


def promote_baseline_model(
    *,
    repository_root: Path,
    runtime_root: Path,
    model_bundle_bytes: bytes,
    report: BacktestReport,
    dataset_manifest: Mapping[str, Any],
    snapshot_symbols: tuple[str, ...],
    as_of: str,
    generated_at: datetime,
    top_k: int,
    per_weight: float,
    feature_names: tuple[str, ...],
) -> PromotionPaths:
    """Create one immutable Champion Package; idempotent for identical content."""
    repository_root = Path(repository_root)
    runtime_root = Path(runtime_root)
    if generated_at.tzinfo is None or generated_at.utcoffset().total_seconds() != 0:
        raise ValueError("promoted_at must be timezone-aware UTC")
    generated_text = generated_at.astimezone(UTC).isoformat().replace("+00:00", "Z")

    cost_model = load_pilot_cost_model(repository_root)
    market_rules = dict(PILOT_MARKET_RULES)
    execution_policy = dict(PILOT_EXECUTION_POLICY)
    portfolio_risk = dict(PILOT_PORTFOLIO_RISK)
    universe = build_universe_document(
        symbols=snapshot_symbols,
        as_of=as_of,
        generated_at=generated_text,
        dataset_manifest=dataset_manifest,
    )

    model_bundle_sha256 = hashlib.sha256(model_bundle_bytes).hexdigest()
    adapter_source = _generate_adapter_source(feature_names)
    adapter_code_bytes = adapter_source.encode()
    config_document = {
        "model_bundle_file": "../../../model/model.bundle",
        "model_bundle_sha256": model_bundle_sha256,
        "top_k": top_k,
        "per_weight": per_weight,
    }
    config_bytes = canonical_json_bytes(config_document) + b"\n"
    code_sha256 = hashlib.sha256(adapter_code_bytes).hexdigest()
    config_sha256 = hashlib.sha256(config_bytes).hexdigest()
    package_sha256 = canonical_json_sha256(
        {
            "adapter_id": ADAPTER_ID,
            "strategy_id": STRATEGY_ID,
            "strategy_version": STRATEGY_VERSION,
            "entrypoint": "adapter.py:build_strategy",
            "code_sha256": code_sha256,
            "config_sha256": config_sha256,
        }
    )
    adapter_manifest = {
        "contract_id": "strategy-adapter",
        "schema_version": "1.0.0",
        "adapter_id": ADAPTER_ID,
        "strategy_id": STRATEGY_ID,
        "strategy_version": STRATEGY_VERSION,
        "entrypoint": "adapter.py:build_strategy",
        "code_file": "adapter.py",
        "code_sha256": code_sha256,
        "config_file": "config.json",
        "config_sha256": config_sha256,
        "package_sha256": package_sha256,
    }

    lockfile = repository_root / "uv.lock"
    lockfile_sha256 = hashlib.sha256(lockfile.read_bytes()).hexdigest()
    universe_snapshot = UniverseSnapshot(
        universe_id=str(universe["universe_id"]),
        universe_policy_id=UNIVERSE_POLICY_ID,
        universe_policy_version=UNIVERSE_POLICY_VERSION,
        source_sha256=canonical_json_sha256(universe),
        as_of=datetime.strptime(as_of, "%Y-%m-%d").date(),
        members=tuple(
            UniverseMember(
                symbol=str(member["symbol"]),
                valid_from=datetime.strptime(member["valid_from"], "%Y-%m-%d").date(),
                valid_to=None,
                eligible=bool(member["eligible"]),
                reason_codes=tuple(member["reason_codes"]),
            )
            for member in universe["members"]
        ),
    )
    promotion_report = {
        "report_id": "pilot-backtest-report/v1",
        "dataset_id": report.dataset_id,
        "snapshot_sha256": report.snapshot_sha256,
        "model_bundle_sha256": report.model_bundle_sha256,
        "train_end": report.train_end.isoformat(),
        "validation_start": report.validation_start.isoformat(),
        "validation_end": report.validation_end.isoformat(),
        "test_start": report.test_start.isoformat(),
        "test_end": report.test_end.isoformat(),
        "validation_ic_mean": report.validation_ic_mean,
        "metrics": dict(report.metrics),
        "leak_checks": [
            {"check_id": check.check_id, "status": check.status, "detail": check.detail}
            for check in report.leak_checks
        ],
    }
    promotion_report_path = runtime_root / "promotion-report.json"
    _write_json(promotion_report_path, promotion_report)

    fixed_contract_set = {
        "cost_model_sha256": canonical_json_sha256(cost_model),
        "market_rules_sha256": canonical_json_sha256(market_rules),
        "execution_policy_sha256": canonical_json_sha256(execution_policy),
        "portfolio_risk_sha256": canonical_json_sha256(portfolio_risk),
        "code_sha256": code_sha256,
        "config_sha256": config_sha256,
        "lockfile_sha256": lockfile_sha256,
    }
    promotion_compatibility = {
        "dataset_family_id": str(dataset_manifest["dataset_family_id"]),
        "data_schema_sha256": str(dataset_manifest["data_schema_sha256"]),
        "normalization_version": str(dataset_manifest["normalization_version"]),
        "universe_policy_id": UNIVERSE_POLICY_ID,
        "universe_policy_version": UNIVERSE_POLICY_VERSION,
    }
    champion = {
        "contract_id": "champion",
        "schema_version": "3.0.0",
        "strategy_id": STRATEGY_ID,
        "strategy_version": STRATEGY_VERSION,
        "adapter_id": ADAPTER_ID,
        "adapter_sha256": package_sha256,
        "promoted_at": generated_text,
        "promotion_compatibility": promotion_compatibility,
        "promotion_evidence": {
            "dataset_manifest_sha256": canonical_json_sha256(dict(dataset_manifest)),
            "dataset_snapshot_sha256": report.snapshot_sha256,
            "universe_snapshot_sha256": universe_snapshot.snapshot_sha256,
        },
        "fixed_contract_set": fixed_contract_set,
        "promotion_report_sha256": canonical_json_sha256(promotion_report),
    }
    champion_schema = _load_schema(repository_root, "champion")
    Draft202012Validator(champion_schema, format_checker=FormatChecker()).validate(champion)
    champion_bytes = canonical_json_bytes(champion) + b"\n"
    champion_sha256 = canonical_json_sha256(champion)

    champion_id = "champ-" + hashlib.sha256(
        canonical_json_bytes(
            {
                "adapter_sha256": package_sha256,
                "fixed_contract_set": fixed_contract_set,
                "promotion_compatibility": promotion_compatibility,
                "promoted_at": generated_text,
            }
        )
    ).hexdigest()[:20]

    receipt = {
        "receipt_id": "champion-promotion-receipt/v1",
        "champion_id": champion_id,
        "champion_sha256": champion_sha256,
        "promotion_id": "promo-" + hashlib.sha256(champion_bytes).hexdigest()[:16],
        "model_bundle_sha256": model_bundle_sha256,
        "adapter_sha256": package_sha256,
        "promoted_at": generated_text,
        "dataset_id": report.dataset_id,
        "snapshot_sha256": report.snapshot_sha256,
        "training_cutoff": report.training_cutoff.isoformat(),
        "production_training_cutoff": report.production_training_cutoff.isoformat(),
        "promotion_report_sha256": canonical_json_sha256(promotion_report),
    }

    champions_dir = runtime_root / "champions"
    package_dir = champions_dir / champion_id
    contracts_dir = package_dir / "contracts"
    adapter_dir = package_dir / "adapter" / Path(*ADAPTER_ID.split("/"))
    model_dir = package_dir / "model"

    if package_dir.exists():
        existing = (package_dir / "champion.json").read_bytes()
        same = existing == champion_bytes
        same = same and (model_dir / "model.bundle").read_bytes() == model_bundle_bytes
        same = same and (adapter_dir / "adapter.py").read_bytes() == adapter_code_bytes
        same = same and (adapter_dir / "config.json").read_bytes() == config_bytes
        if not same:
            raise ChampionPackageError(
                f"champion package {champion_id} exists with different content"
            )
    else:
        champions_dir.mkdir(parents=True, exist_ok=True)
        temporary = champions_dir / f".{champion_id}.tmp"
        if temporary.exists():
            shutil.rmtree(temporary)
        try:
            _write_json(temporary / "champion.json", champion)
            _write_json(temporary / "promotion-receipt.json", receipt)
            _write_json(temporary / "contracts" / "cost-model.json", cost_model)
            _write_json(temporary / "contracts" / "market-rules.json", market_rules)
            _write_json(temporary / "contracts" / "execution-policy.json", execution_policy)
            _write_json(temporary / "contracts" / "portfolio-risk.json", portfolio_risk)
            _write_json(temporary / "contracts" / "universe.json", universe)
            _write_json(
                temporary / "contracts" / "dataset-manifest.json", dict(dataset_manifest)
            )
            _write_json(temporary / "adapter" / Path(*ADAPTER_ID.split("/")) / "adapter.json",
                        adapter_manifest)
            (temporary / "adapter" / Path(*ADAPTER_ID.split("/"))).mkdir(
                parents=True, exist_ok=True
            )
            (temporary / "adapter" / Path(*ADAPTER_ID.split("/")) / "adapter.py").write_bytes(
                adapter_code_bytes
            )
            (temporary / "adapter" / Path(*ADAPTER_ID.split("/")) / "config.json").write_bytes(
                config_bytes
            )
            (temporary / "model").mkdir(parents=True, exist_ok=True)
            (temporary / "model" / "model.bundle").write_bytes(model_bundle_bytes)
            os.replace(temporary, package_dir)
        except BaseException:
            shutil.rmtree(temporary, ignore_errors=True)
            raise

    return PromotionPaths(
        runtime_root=runtime_root,
        champions_dir=champions_dir,
        package_dir=package_dir,
        contracts_dir=contracts_dir,
        adapter_root=package_dir / "adapter",
        champion_path=package_dir / "champion.json",
        receipt_path=package_dir / "promotion-receipt.json",
        promotion_report_path=promotion_report_path,
        model_bundle_path=model_dir / "model.bundle",
        champion_id=champion_id,
        champion_sha256=champion_sha256,
    )


def load_active_champion(runtime_root: Path) -> dict[str, Any] | None:
    pointer_path = Path(runtime_root) / "active-champion.json"
    if not pointer_path.is_file():
        return None
    document = json.loads(pointer_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ChampionPackageError("active champion pointer must be an object")
    return document


def activate_champion(
    *,
    runtime_root: Path,
    champion_id: str,
    activated_at: datetime,
) -> dict[str, Any]:
    """Verify a frozen package, then atomically flip the active pointer."""
    runtime_root = Path(runtime_root)
    if activated_at.tzinfo is None or activated_at.utcoffset().total_seconds() != 0:
        raise ValueError("activated_at must be timezone-aware UTC")
    package_dir = runtime_root / "champions" / champion_id
    if not package_dir.is_dir():
        raise ChampionPackageError(f"champion package does not exist: {champion_id}")
    champion = json.loads((package_dir / "champion.json").read_text(encoding="utf-8"))
    receipt = json.loads((package_dir / "promotion-receipt.json").read_text(encoding="utf-8"))
    if receipt.get("champion_id") != champion_id:
        raise ChampionPackageError("receipt champion_id does not match package")

    adapter_dir = package_dir / "adapter" / Path(*str(champion["adapter_id"]).split("/"))
    manifest = json.loads((adapter_dir / "adapter.json").read_text(encoding="utf-8"))
    code_bytes = (adapter_dir / "adapter.py").read_bytes()
    config_bytes = (adapter_dir / "config.json").read_bytes()
    if hashlib.sha256(code_bytes).hexdigest() != manifest["code_sha256"]:
        raise ChampionPackageError("adapter code hash mismatch in frozen package")
    if hashlib.sha256(config_bytes).hexdigest() != manifest["config_sha256"]:
        raise ChampionPackageError("adapter config hash mismatch in frozen package")
    expected_package = canonical_json_sha256(
        {
            "adapter_id": manifest["adapter_id"],
            "strategy_id": manifest["strategy_id"],
            "strategy_version": manifest["strategy_version"],
            "entrypoint": manifest["entrypoint"],
            "code_sha256": manifest["code_sha256"],
            "config_sha256": manifest["config_sha256"],
        }
    )
    if expected_package != manifest["package_sha256"]:
        raise ChampionPackageError("adapter package sha mismatch in frozen package")
    if manifest["package_sha256"] != champion["adapter_sha256"]:
        raise ChampionPackageError("champion adapter_sha256 does not match adapter manifest")
    bundle_bytes = (package_dir / "model" / "model.bundle").read_bytes()
    if hashlib.sha256(bundle_bytes).hexdigest() != receipt["model_bundle_sha256"]:
        raise ChampionPackageError("model bundle hash mismatch in frozen package")

    pointer = {
        "pointer_id": "active-champion/v1",
        "champion_id": champion_id,
        "champion_sha256": canonical_json_sha256(champion),
        "activated_at": activated_at.astimezone(UTC).isoformat().replace("+00:00", "Z"),
        "promotion_id": str(receipt["promotion_id"]),
    }
    pointer_path = runtime_root / "active-champion.json"
    pointer_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = pointer_path.with_name(f".{pointer_path.name}.tmp")
    temporary.write_bytes(canonical_json_bytes(pointer) + b"\n")
    os.replace(temporary, pointer_path)
    return pointer
