"""Promote the trained baseline model into immutable champion artifacts.

Outputs (all under an explicit runtime root, never in Git):
  - runtime contract documents (universe, cost, market rules, execution,
    portfolio risk) for the pilot;
  - one content-addressed strategy adapter package embedding the model
    bundle;
  - one Champion 3.0 document binding every contract hash.
"""

from __future__ import annotations

import hashlib
import inspect
import json
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ashare_quant_core import UniverseMember, UniverseSnapshot
from jsonschema import Draft202012Validator, FormatChecker

from .backtest import BacktestReport
from .features import MIN_OBSERVATIONS, _return, compute_feature_row

ADAPTER_ID = "ml-baseline-adapter/v1"
STRATEGY_ID = "ml-baseline"
STRATEGY_VERSION = "v1"
UNIVERSE_POLICY_ID = "pilot-audit-universe"
UNIVERSE_POLICY_VERSION = "v1"
PILOT_MARKET_RULES: dict[str, Any] = {
    "contract_id": "market-rules",
    "schema_version": "1.0.0",
    "rules_id": "pilot-a-share-market/v1",
    "segments": [
        {
            "segment_id": f"{board}-normal",
            "board": board,
            "security_status": "normal",
            "valid_from": "2020-01-01",
            "valid_to": None,
            "lot_size": 100,
            "sell_t_plus": 1,
            "price_limit_pct": 0.2 if board in {"gem", "star"} else 0.1,
        }
        for board in ("main", "gem", "star")
    ],
}
PILOT_EXECUTION_POLICY: dict[str, Any] = {
    "contract_id": "execution-policy",
    "schema_version": "1.0.0",
    "policy_id": "pilot-next-open/v1",
    "decision_timing": "daily_close",
    "execution_timing": "next_open",
    "slippage_bps": 10,
    "impact_model": "linear_participation",
    "maximum_participation_rate": 0.05,
    "enforce_t_plus_one": True,
}
PILOT_PORTFOLIO_RISK: dict[str, Any] = {
    "contract_id": "portfolio-risk",
    "schema_version": "1.0.0",
    "risk_id": "pilot-aggressive-long-only/v1",
    "max_positions": 6,
    "max_single_weight": 0.25,
    "max_theme_weight": 1.0,
    "max_gross_exposure": 1.0,
    "rebalance_threshold": 0.02,
}

ADAPTER_SOURCE_TEMPLATE = '''\
"""Baseline ML adapter generated by research promotion. Do not edit by hand."""

from __future__ import annotations

import hashlib
import math
import pickle
from collections import defaultdict
from collections.abc import Mapping, Sequence
from datetime import date
from pathlib import Path

import numpy as np
from ashare_quant_core import DailyBar, DatasetSnapshot, TargetPosition, UniverseSnapshot

FEATURE_NAMES = {feature_names}
MIN_OBSERVATIONS = {min_observations}


{return_source}


{compute_feature_row_source}


class BaselineMLStrategy:
    strategy_id = "{strategy_id}"
    strategy_version = "{strategy_version}"

    def __init__(self, *, bundle, top_k: int, per_weight: float) -> None:
        self._models = bundle["models"]
        self._horizons = tuple(bundle["horizons"])
        self._top_k = top_k
        self._per_weight = per_weight

    def _score(self, matrix):
        predictions = np.column_stack(
            [self._models[horizon].predict(matrix) for horizon in self._horizons]
        )
        return predictions.mean(axis=1)

    def target_positions(
        self,
        *,
        as_of: date,
        dataset_snapshot: DatasetSnapshot,
        universe_snapshot: UniverseSnapshot,
    ) -> tuple[TargetPosition, ...]:
        history: dict[str, list[DailyBar]] = defaultdict(list)
        for bar in dataset_snapshot.bars(through=as_of):
            if bar.symbol in universe_snapshot.eligible_symbols:
                history[bar.symbol].append(bar)

        candidates: list[tuple[str, tuple[float, ...]]] = []
        for symbol in sorted(history):
            ordered = sorted(history[symbol], key=lambda item: item.trade_date)
            if ordered[-1].trade_date > as_of:
                continue
            values = compute_feature_row(ordered, len(ordered) - 1)
            if values is None:
                continue
            candidates.append((symbol, values))
        if not candidates:
            return ()

        matrix = np.asarray([values for _, values in candidates], dtype=float)
        scores = self._score(matrix)
        ranked = sorted(
            ((symbol, float(score)) for (symbol, _), score in zip(candidates, scores)),
            key=lambda item: (-item[1], item[0]),
        )
        return tuple(
            TargetPosition(symbol=symbol, target_weight=self._per_weight)
            for symbol, _ in ranked[: self._top_k]
        )


def build_strategy(config: Mapping[str, object]) -> BaselineMLStrategy:
    package_dir = Path(__file__).resolve().parent
    bundle_path = package_dir / str(config["model_bundle_file"])
    if bundle_path.is_symlink():
        raise ValueError("model bundle cannot be a symlink")
    content = bundle_path.read_bytes()
    if hashlib.sha256(content).hexdigest() != config["model_bundle_sha256"]:
        raise ValueError("model bundle hash mismatch")
    bundle = pickle.loads(content)
    return BaselineMLStrategy(
        bundle=bundle,
        top_k=int(config["top_k"]),
        per_weight=float(config["per_weight"]),
    )
'''


def canonical_json_bytes(document: Mapping[str, Any]) -> bytes:
    return json.dumps(document, ensure_ascii=True, separators=(",", ":"), sort_keys=True).encode()


def canonical_json_sha256(document: Mapping[str, Any]) -> str:
    return hashlib.sha256(canonical_json_bytes(document)).hexdigest()


def _write_json(path: Path, document: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical_json_bytes(document) + b"\n")


def _load_schema(repository_root: Path, contract_id: str) -> dict[str, Any]:
    registry = json.loads((repository_root / "contracts/registry.json").read_text(encoding="utf-8"))
    for entry in registry["contracts"]:
        if entry["contract_id"] == contract_id:
            schema = json.loads((repository_root / "contracts" / entry["schema"]).read_text())
            if isinstance(schema, dict):
                return schema
    raise ValueError(f"missing schema for {contract_id}")


def build_universe_document(
    *,
    symbols: tuple[str, ...],
    as_of: str,
    generated_at: str,
    dataset_manifest: Mapping[str, Any],
) -> dict[str, Any]:
    if not symbols:
        raise ValueError("pilot universe requires at least one symbol")
    valid_from = str(dataset_manifest["files"][0]["min_trade_date"])
    members = [
        {
            "symbol": symbol,
            "valid_from": valid_from,
            "valid_to": None,
            "eligible": True,
            "reason_codes": ["PILOT_MEMBER", "DATA_COMPLETE"],
        }
        for symbol in sorted(set(symbols))
    ]
    return {
        "contract_id": "universe",
        "schema_version": "2.0.0",
        "universe_id": "pilot-audit-universe-pit/v1",
        "universe_policy_id": UNIVERSE_POLICY_ID,
        "universe_policy_version": UNIVERSE_POLICY_VERSION,
        "as_of": as_of,
        "generated_at": generated_at,
        "source": "pilot-universe-generator/v1",
        "source_version": "v1",
        "quality_status": "pass",
        "members": members,
    }


def load_pilot_cost_model(repository_root: Path) -> dict[str, Any]:
    document = json.loads(
        (repository_root / "contracts/examples/cost-model.example.json").read_text(
            encoding="utf-8"
        )
    )
    if not isinstance(document, dict):
        raise ValueError("cost model example must be an object")
    return document


@dataclass(frozen=True)
class PromotionPaths:
    runtime_root: Path
    contracts_dir: Path
    adapter_root: Path
    champion_path: Path
    promotion_report_path: Path
    model_bundle_path: Path


def _generate_adapter_source(feature_names: tuple[str, ...]) -> str:
    return ADAPTER_SOURCE_TEMPLATE.format(
        feature_names=repr(feature_names),
        min_observations=MIN_OBSERVATIONS,
        return_source=inspect.getsource(_return),
        compute_feature_row_source=inspect.getsource(compute_feature_row),
        strategy_id=STRATEGY_ID,
        strategy_version=STRATEGY_VERSION,
    )


def promote_baseline_model(
    *,
    repository_root: Path,
    runtime_root: Path,
    model_bundle_bytes: bytes,
    report: BacktestReport,
    dataset_manifest: Mapping[str, Any],
    snapshot_symbols: tuple[str, ...],
    as_of: str,
    generated_at: datetime,
    top_k: int,
    per_weight: float,
    feature_names: tuple[str, ...],
) -> PromotionPaths:
    """Write champion, adapter package, and runtime contracts atomically."""
    repository_root = Path(repository_root)
    runtime_root = Path(runtime_root)
    contracts_dir = runtime_root / "contracts"
    adapter_root = runtime_root / "adapters"
    package_dir = adapter_root.joinpath(*ADAPTER_ID.split("/"))

    if generated_at.tzinfo is None or generated_at.utcoffset().total_seconds() != 0:
        raise ValueError("promoted_at must be timezone-aware UTC")
    generated_text = generated_at.astimezone(UTC).isoformat().replace("+00:00", "Z")

    cost_model = load_pilot_cost_model(repository_root)
    market_rules = dict(PILOT_MARKET_RULES)
    execution_policy = dict(PILOT_EXECUTION_POLICY)
    portfolio_risk = dict(PILOT_PORTFOLIO_RISK)
    universe = build_universe_document(
        symbols=snapshot_symbols,
        as_of=as_of,
        generated_at=generated_text,
        dataset_manifest=dataset_manifest,
    )
    _write_json(contracts_dir / "cost-model.json", cost_model)
    _write_json(contracts_dir / "market-rules.json", market_rules)
    _write_json(contracts_dir / "execution-policy.json", execution_policy)
    _write_json(contracts_dir / "portfolio-risk.json", portfolio_risk)
    _write_json(contracts_dir / "universe.json", universe)
    _write_json(contracts_dir / "dataset-manifest.json", dict(dataset_manifest))

    model_bundle_sha256 = hashlib.sha256(model_bundle_bytes).hexdigest()
    package_dir.mkdir(parents=True, exist_ok=True)
    model_bundle_path = package_dir / "model.bundle"
    model_bundle_path.write_bytes(model_bundle_bytes)

    adapter_source = _generate_adapter_source(feature_names)
    adapter_code_bytes = adapter_source.encode()
    config_document = {
        "model_bundle_file": "model.bundle",
        "model_bundle_sha256": model_bundle_sha256,
        "top_k": top_k,
        "per_weight": per_weight,
    }
    config_bytes = canonical_json_bytes(config_document) + b"\n"
    (package_dir / "adapter.py").write_bytes(adapter_code_bytes)
    (package_dir / "config.json").write_bytes(config_bytes)
    code_sha256 = hashlib.sha256(adapter_code_bytes).hexdigest()
    config_sha256 = hashlib.sha256(config_bytes).hexdigest()
    package_sha256 = canonical_json_sha256(
        {
            "adapter_id": ADAPTER_ID,
            "strategy_id": STRATEGY_ID,
            "strategy_version": STRATEGY_VERSION,
            "entrypoint": "adapter.py:build_strategy",
            "code_sha256": code_sha256,
            "config_sha256": config_sha256,
        }
    )
    adapter_manifest = {
        "contract_id": "strategy-adapter",
        "schema_version": "1.0.0",
        "adapter_id": ADAPTER_ID,
        "strategy_id": STRATEGY_ID,
        "strategy_version": STRATEGY_VERSION,
        "entrypoint": "adapter.py:build_strategy",
        "code_file": "adapter.py",
        "code_sha256": code_sha256,
        "config_file": "config.json",
        "config_sha256": config_sha256,
        "package_sha256": package_sha256,
    }
    _write_json(package_dir / "adapter.json", adapter_manifest)

    lockfile = repository_root / "uv.lock"
    lockfile_sha256 = hashlib.sha256(lockfile.read_bytes()).hexdigest()
    universe_snapshot = UniverseSnapshot(
        universe_id=str(universe["universe_id"]),
        universe_policy_id=UNIVERSE_POLICY_ID,
        universe_policy_version=UNIVERSE_POLICY_VERSION,
        source_sha256=canonical_json_sha256(universe),
        as_of=datetime.strptime(as_of, "%Y-%m-%d").date(),
        members=tuple(
            UniverseMember(
                symbol=str(member["symbol"]),
                valid_from=datetime.strptime(member["valid_from"], "%Y-%m-%d").date(),
                valid_to=None,
                eligible=bool(member["eligible"]),
                reason_codes=tuple(member["reason_codes"]),
            )
            for member in universe["members"]
        ),
    )
    promotion_report = {
        "report_id": "pilot-backtest-report/v1",
        "dataset_id": report.dataset_id,
        "snapshot_sha256": report.snapshot_sha256,
        "model_bundle_sha256": report.model_bundle_sha256,
        "train_end": report.train_end.isoformat(),
        "validation_start": report.validation_start.isoformat(),
        "validation_end": report.validation_end.isoformat(),
        "test_start": report.test_start.isoformat(),
        "test_end": report.test_end.isoformat(),
        "validation_ic_mean": report.validation_ic_mean,
        "metrics": dict(report.metrics),
        "leak_checks": [
            {"check_id": check.check_id, "status": check.status, "detail": check.detail}
            for check in report.leak_checks
        ],
    }
    promotion_report_path = runtime_root / "promotion-report.json"
    _write_json(promotion_report_path, promotion_report)

    champion = {
        "contract_id": "champion",
        "schema_version": "3.0.0",
        "strategy_id": STRATEGY_ID,
        "strategy_version": STRATEGY_VERSION,
        "adapter_id": ADAPTER_ID,
        "adapter_sha256": package_sha256,
        "promoted_at": generated_text,
        "promotion_compatibility": {
            "dataset_family_id": str(dataset_manifest["dataset_family_id"]),
            "data_schema_sha256": str(dataset_manifest["data_schema_sha256"]),
            "normalization_version": str(dataset_manifest["normalization_version"]),
            "universe_policy_id": UNIVERSE_POLICY_ID,
            "universe_policy_version": UNIVERSE_POLICY_VERSION,
        },
        "promotion_evidence": {
            "dataset_manifest_sha256": canonical_json_sha256(dict(dataset_manifest)),
            "dataset_snapshot_sha256": report.snapshot_sha256,
            "universe_snapshot_sha256": universe_snapshot.snapshot_sha256,
        },
        "fixed_contract_set": {
            "cost_model_sha256": canonical_json_sha256(cost_model),
            "market_rules_sha256": canonical_json_sha256(market_rules),
            "execution_policy_sha256": canonical_json_sha256(execution_policy),
            "portfolio_risk_sha256": canonical_json_sha256(portfolio_risk),
            "code_sha256": code_sha256,
            "config_sha256": config_sha256,
            "lockfile_sha256": lockfile_sha256,
        },
        "promotion_report_sha256": canonical_json_sha256(promotion_report),
    }
    champion_schema = _load_schema(repository_root, "champion")
    Draft202012Validator(champion_schema, format_checker=FormatChecker()).validate(champion)
    champion_path = contracts_dir / "champion.json"
    _write_json(champion_path, champion)

    return PromotionPaths(
        runtime_root=runtime_root,
        contracts_dir=contracts_dir,
        adapter_root=adapter_root,
        champion_path=champion_path,
        promotion_report_path=promotion_report_path,
        model_bundle_path=model_bundle_path,
    )
